filter:
    paths: ["app/*"]

checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage:
        timeout: 600

    php_analyzer: true
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: "PSR2"

    # PHP CS Fixer (http://http://cs.sensiolabs.org/).
    php_cs_fixer:
        enabled: true
        config:
            level: psr2

    # Analyzes the size and structure of a PHP project.
    php_loc: true

    # Security Advisory Checker
    sensiolabs_security_checker: true
